import { validateContent } from "./schema";
export const fixture = validateContent({
  version: "world-01-v14",
  tickMs: 100,
  containmentCapabilities: [
    {
      id: "corrosion-resistant",
      nameKey: "containment.corrosion-resistant.name",
    },
    {
      id: "cryogenic-rated",
      nameKey: "containment.cryogenic-rated.name",
    },
    {
      id: "hazard-isolated",
      nameKey: "containment.hazard-isolated.name",
    },
    {
      id: "secure-chain",
      nameKey: "containment.secure-chain.name",
    },
  ],
  hazardClasses: [
    {
      id: "thermal-runaway",
      nameKey: "hazard.class.thermal-runaway.name",
      evidenceKey: "hazard.class.thermal-runaway.evidence",
      machineEffect: "lockout",
    },
    {
      id: "pressure-expansion",
      nameKey: "hazard.class.pressure-expansion.name",
      evidenceKey: "hazard.class.pressure-expansion.evidence",
      machineEffect: "lockout",
    },
    {
      id: "corrosion",
      nameKey: "hazard.class.corrosion.name",
      evidenceKey: "hazard.class.corrosion.evidence",
      machineEffect: "lockout",
    },
    {
      id: "instability",
      nameKey: "hazard.class.instability.name",
      evidenceKey: "hazard.class.instability.evidence",
      machineEffect: "lockout",
      strandedOutputUnits: 1,
    },
    {
      id: "contamination",
      nameKey: "hazard.class.contamination.name",
      evidenceKey: "hazard.class.contamination.evidence",
      machineEffect: "lockout",
    },
  ],
  gasLogistics: {
    line: { capacity: 4, transfer: 1, cost: 3 },
    vessel: { capacity: 48, width: 2, height: 2, cost: 28 },
    compressor: { transfer: 1, fuel: 1, cost: 16 },
  },
  liquidLogistics: {
    pipe: { capacity: 4, transfer: 1, cost: 2 },
    tank: { capacity: 64, width: 2, height: 2, cost: 24 },
    pump: { transfer: 1, fuel: 1, cost: 12, containmentFailure: {
      id: "pump-corrosion", nameKey: "handling.failure.pump-corrosion.name",
      descriptionKey: "handling.failure.pump-corrosion.description",
      exposedProfileId: "standard", missingCapabilityId: "corrosion-resistant", trappedCapacity: 1,
    } },
    containmentProfiles: [
      {
        id: "standard",
        nameKey: "containment.profile.standard.name",
        capabilities: [],
        additionalCost: { pipe: 0, tank: 0, pump: 0 },
      },
      {
        id: "lined",
        nameKey: "containment.profile.lined.name",
        capabilities: ["corrosion-resistant"],
        additionalCost: { pipe: 2, tank: 10, pump: 4 },
      },
      {
        id: "sealed-cold",
        nameKey: "containment.profile.sealed-cold.name",
        capabilities: ["cryogenic-rated", "hazard-isolated", "secure-chain"],
        additionalCost: { pipe: 4, tank: 14, pump: 6 },
      },
    ],
  },
  materials: [
    {
      id: "gas-0",
      nameKey: "material.gas-0.name",
      color: "#dbbf7f",
      known: false,
      handlingState: "gas",
    },
    {
      id: "liquid-0",
      requiredContainment: ["corrosion-resistant"],
      nameKey: "material.liquid-0.name",
      color: "#69bac8",
      known: false,
      handlingState: "liquid",
    },
    {
      id: "ferrite",
      nameKey: "material.ferrite.name",
      color: "#a88d78",
      known: true,
    },
    {
      id: "plates",
      nameKey: "material.plates.name",
      color: "#b7c6ad",
      known: true,
    },
    {
      id: "ferrite-ceramic",
      nameKey: "material.ferrite-ceramic.name",
      color: "#c98f72",
      known: false,
    },
    {
      id: "raw",
      nameKey: "material.raw.name",
      color: "#c8aa73",
      known: true,
    },
    {
      id: "granules",
      nameKey: "material.granules.name",
      color: "#aadea0",
      known: false,
    },
    {
      id: "residue",
      nameKey: "material.residue.name",
      color: "#b298c4",
      known: false,
    },
    {
      id: "catalyst",
      nameKey: "material.catalyst.name",
      color: "#d5c4a1",
      known: true,
    },
    {
      id: "catalyst-powder",
      nameKey: "material.catalyst-powder.name",
      color: "#d8cfb9",
      known: false,
    },
    {
      id: "orbital-binder",
      nameKey: "material.orbital-binder.name",
      color: "#9eb6d8",
      known: true,
    },
    {
      id: "orbital-propellant",
      nameKey: "material.orbital-propellant.name",
      color: "#a8c4de",
      known: true,
      handlingState: "gas",
    },
    {
      id: "orbital-coolant",
      nameKey: "material.orbital-coolant.name",
      color: "#9fd8e5",
      known: true,
      handlingState: "liquid",
      requiredContainment: ["cryogenic-rated", "hazard-isolated", "secure-chain"],
    },
    {
      id: "matrix",
      nameKey: "material.matrix.name",
      color: "#8fd1c8",
      known: false,
    },
  ],
  fuelClasses: [
    {
      id: "advanced-propellant",
      nameKey: "fuel.class.advanced-propellant.name",
      materialId: "orbital-propellant",
      terminalModuleId: "gas-dock",
      requiredMilestoneId: "gas-study-certified",
    },
    {
      id: "research-coolant",
      nameKey: "fuel.class.research-coolant.name",
      materialId: "orbital-coolant",
      terminalModuleId: "cryo-dock",
      requiredMilestoneId: "resonance-survey-certified",
    },
  ],
  operations: [
    { id: "vaporize", nameKey: "operation.vaporize.name" },
    { id: "collect-gas", nameKey: "operation.collect-gas.name" },
    { id: "liquefy", nameKey: "operation.liquefy.name" },
    { id: "precipitate", nameKey: "operation.precipitate.name" },
    { id: "crush", nameKey: "operation.crush.name" },
    { id: "heat", nameKey: "operation.heat.name" },
    { id: "sinter", nameKey: "operation.sinter.name" },
  ],
  machines: [
    {
      id: "vaporizer",
      inputContainment: ["corrosion-resistant"],
      nameKey: "machine.vaporizer.name",
      role: "processor",
      operations: ["vaporize"],
      inputStates: ["liquid"],
      outputStates: ["gas"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 32,
    },
    {
      id: "gas-collector",
      nameKey: "machine.gas-collector.name",
      role: "processor",
      operations: ["collect-gas"],
      inputStates: ["gas"],
      outputStates: ["solid"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 32,
    },
    {
      id: "liquefier",
      outputContainment: ["corrosion-resistant"],
      nameKey: "machine.liquefier.name",
      role: "processor",
      operations: ["liquefy"],
      inputStates: ["solid"],
      outputStates: ["liquid"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 32,
    },
    {
      id: "precipitator",
      inputContainment: ["corrosion-resistant"],
      nameKey: "machine.precipitator.name",
      role: "processor",
      operations: ["precipitate"],
      inputStates: ["liquid"],
      outputStates: ["solid"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 32,
    },
    {
      id: "extractor",
      nameKey: "machine.extractor.name",
      role: "extractor",
      operations: [],
      capacity: 8,
      fuel: 1,
      durationTicks: 20,
      width: 2,
      height: 2,
      cost: 18,
    },
    {
      id: "deep-extractor",
      nameKey: "machine.deep-extractor.name",
      role: "extractor",
      maxExtractionDepth: 20,
      fuelClassId: "advanced-propellant",
      unlock: {
        reactionId: "heat-raw-sealed",
        hintKey: "machine.deep-extractor.unlock-hint",
      },
      operations: [],
      capacity: 8,
      fuel: 1,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 36,
    },
    {
      id: "atmospheric-intake",
      nameKey: "machine.atmospheric-intake.name",
      role: "extractor",
      sourceKind: "atmosphere",
      unlock: {
        reactionId: "vaporize-liquid-0",
        hintKey: "machine.atmospheric-intake.unlock-hint",
      },
      operations: [],
      outputStates: ["gas"],
      capacity: 8,
      fuel: 2,
      durationTicks: 20,
      width: 2,
      height: 2,
      cost: 28,
    },
    {
      id: "sinterer",
      nameKey: "machine.sinterer.name",
      role: "processor",
      fuelClassId: "research-coolant",
      operations: ["sinter"],
      capacity: 12,
      fuel: 1,
      durationTicks: 36,
      width: 2,
      height: 2,
      cost: 34,
    },
    {
      id: "crusher",
      nameKey: "machine.crusher.name",
      role: "processor",
      operations: ["crush"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 24,
    },
    {
      id: "furnace",
      nameKey: "machine.furnace.name",
      role: "processor",
      processConditionId: "ambient",
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 26,
    },
    {
      id: "sealed-furnace",
      nameKey: "machine.sealed-furnace.name",
      role: "processor",
      processConditionId: "sealed",
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 26,
    },
    {
      id: "oversealed-furnace",
      nameKey: "machine.oversealed-furnace.name",
      role: "processor",
      processConditionId: "oversealed",
      unlock: {
        reactionId: "heat-raw-sealed",
        hintKey: "machine.oversealed-furnace.unlock-hint",
      },
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 30,
    },
    {
      id: "relief-furnace",
      nameKey: "machine.relief-furnace.name",
      role: "processor",
      processConditionId: "relieved",
      unlock: {
        hazardEvidenceId: "slag-jam",
        hintKey: "machine.relief-furnace.unlock-hint",
      },
      operations: ["heat"],
      capacity: 12,
      fuel: 3,
      durationTicks: 32,
      width: 2,
      height: 2,
      cost: 34,
    },
  ],
  junctions: [
    {
      id: "splitter",
      kind: "splitter",
      nameKey: "junction.splitter.name",
      cost: 8,
    },
    { id: "merger", kind: "merger", nameKey: "junction.merger.name", cost: 8 },
    {
      id: "crossing",
      kind: "crossing",
      nameKey: "junction.crossing.name",
      cost: 12,
      windowSteps: 4,
    },
  ],
  storages: [
    {
      id: "depot",
      nameKey: "storage.depot.name",
      capacity: 40,
      width: 3,
      height: 2,
      cost: 30,
    },
  ],
  reactions: [
    {
      id: "vaporize-liquid-0",
      operation: "vaporize",
      input: "liquid-0",
      inputAmount: 1,
      output: "gas-0",
      outputAmount: 1,
      observationKey: "reaction.vaporize-liquid-0.observation",
      known: false,
    },
    {
      id: "collect-gas-0",
      operation: "collect-gas",
      input: "gas-0",
      inputAmount: 1,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.collect-gas-0.observation",
      known: false,
    },
    {
      id: "liquefy-raw",
      operation: "liquefy",
      input: "raw",
      inputAmount: 2,
      output: "liquid-0",
      outputAmount: 2,
      observationKey: "reaction.liquefy-raw.observation",
      known: false,
    },
    {
      id: "precipitate-liquid-0",
      operation: "precipitate",
      input: "liquid-0",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.precipitate-liquid-0.observation",
      known: false,
    },
    {
      id: "press-ferrite",
      operation: "crush",
      input: "ferrite",
      inputAmount: 2,
      output: "plates",
      outputAmount: 6,
      observationKey: "reaction.press-ferrite.observation",
      known: true,
    },
    {
      id: "heat-ferrite",
      operation: "heat",
      processConditionId: "ambient",
      input: "ferrite",
      inputAmount: 2,
      output: "ferrite-ceramic",
      outputAmount: 1,
      observationKey: "reaction.heat-ferrite.observation",
      known: false,
    },
    {
      id: "crush-raw",
      operation: "crush",
      input: "raw",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.crush-raw.observation",
      known: false,
    },
    {
      id: "heat-raw",
      operation: "heat",
      processConditionId: "ambient",
      input: "raw",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-raw.observation",
      known: false,
    },
    {
      id: "heat-raw-sealed",
      operation: "heat",
      processConditionId: "sealed",
      input: "raw",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.heat-raw-sealed.observation",
      known: false,
    },
    {
      id: "sinter-orbital-binder",
      operation: "sinter",
      input: "orbital-binder",
      inputAmount: 2,
      output: "matrix",
      outputAmount: 1,
      observationKey: "reaction.sinter-orbital-binder.observation",
      known: false,
    },
    {
      id: "sinter-catalyst",
      operation: "sinter",
      input: "catalyst",
      inputAmount: 2,
      output: "matrix",
      outputAmount: 1,
      observationKey: "reaction.sinter-catalyst.observation",
      known: false,
    },
    {
      id: "crush-catalyst",
      operation: "crush",
      input: "catalyst",
      inputAmount: 2,
      output: "catalyst-powder",
      outputAmount: 1,
      observationKey: "reaction.crush-catalyst.observation",
      known: false,
    },
    {
      id: "heat-raw-oversealed",
      operation: "heat",
      processConditionId: "oversealed",
      input: "raw",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-raw-oversealed.observation",
      hazard: {
        id: "chamber-blowout",
        classId: "pressure-expansion",
        nameKey: "hazard.chamber-blowout.name",
        observationKey: "hazard.chamber-blowout.observation",
        saferHintKey: "hazard.chamber-blowout.safer-hint",
      },
      known: false,
    },
    {
      id: "heat-ferrite-sealed",
      operation: "heat",
      processConditionId: "sealed",
      input: "ferrite",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-ferrite-sealed.observation",
      known: false,
    },
    {
      id: "heat-ferrite-relieved",
      operation: "heat",
      processConditionId: "relieved",
      input: "ferrite",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-ferrite-relieved.observation",
      known: false,
    },
    {
      id: "heat-ferrite-oversealed",
      operation: "heat",
      processConditionId: "oversealed",
      input: "ferrite",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-ferrite-oversealed.observation",
      hazard: {
        id: "slag-jam",
        classId: "instability",
        nameKey: "hazard.slag-jam.name",
        observationKey: "hazard.slag-jam.observation",
        saferHintKey: "hazard.slag-jam.safer-hint",
      },
      known: false,
    },
  ],
  knowledgeInsights: [
    {
      id: "ferrite-capital",
      materialId: "ferrite",
      kind: "property",
      textKey: "knowledge.insight.ferrite-capital.text",
      requires: { type: "material-known", materialId: "ferrite" },
    },
    {
      id: "ferrite-thermal-branch",
      materialId: "ferrite",
      kind: "branch",
      textKey: "knowledge.insight.ferrite-thermal-branch.text",
      requires: { type: "material-known", materialId: "ferrite" },
    },
    {
      id: "ferrite-ceramic-market",
      materialId: "ferrite-ceramic",
      kind: "opportunity",
      textKey: "knowledge.insight.ferrite-ceramic-market.text",
      requires: {
        type: "reaction-evidence",
        reactionId: "heat-ferrite",
        state: "confirmed",
      },
    },
    {
      id: "veined-multi-state",
      materialId: "raw",
      kind: "branch",
      textKey: "knowledge.insight.veined-multi-state.text",
      requires: { type: "material-known", materialId: "raw" },
    },
    {
      id: "corrosive-liquid",
      materialId: "liquid-0",
      kind: "property",
      textKey: "knowledge.insight.corrosive-liquid.text",
      requires: {
        type: "reaction-evidence",
        reactionId: "liquefy-raw",
        state: "confirmed",
      },
    },
    {
      id: "catalyst-choice",
      materialId: "catalyst",
      kind: "branch",
      textKey: "knowledge.insight.catalyst-choice.text",
      requires: { type: "material-known", materialId: "catalyst" },
    },
    {
      id: "catalyst-powder-market",
      materialId: "catalyst-powder",
      kind: "opportunity",
      textKey: "knowledge.insight.catalyst-powder-market.text",
      requires: {
        type: "reaction-evidence",
        reactionId: "crush-catalyst",
        state: "confirmed",
      },
    },
    {
      id: "matrix-local-value",
      materialId: "matrix",
      kind: "opportunity",
      textKey: "knowledge.insight.matrix-local-value.text",
      requires: {
        type: "reaction-evidence",
        reactionId: "sinter-catalyst",
        state: "confirmed",
      },
    },
  ],
  site: {
    sensingCapabilities: [
      {
        id: "survey-scanner",
        nameKey: "sensing.capability.survey-scanner.name",
        mode: "scan",
        range: 8,
      },
      {
        id: "core-probe",
        nameKey: "sensing.capability.core-probe.name",
        mode: "probe",
        range: 1,
        requiredMilestoneId: "sealed-study-certified",
      },
      {
        id: "resonance-probe",
        nameKey: "sensing.capability.resonance-probe.name",
        mode: "probe",
        range: 1,
        requiredMilestoneId: "resonance-survey-certified",
      },
    ],
    surveySignals: [
      { id: "anomaly-a", x: 46, y: 18, strength: 8, depth: 14 },
      { id: "anomaly-b", x: 62, y: 42, strength: 5, depth: 4 },
      { id: "anomaly-c", x: 70, y: 26, strength: 7, depth: 1 },
      { id: "anomaly-d", x: 57, y: 10, strength: 8, depth: 9 },
    ],
    hiddenDeposits: [
      {
        id: "deep-vein-a",
        material: "raw",
        x: 43,
        y: 15,
        width: 5,
        height: 7,
        units: 1200,
        surveySignalId: "anomaly-a",
        requiredSensingCapabilityId: "core-probe",
      },
      {
        id: "catalyst-seam-a",
        material: "catalyst",
        x: 55,
        y: 8,
        width: 5,
        height: 5,
        units: 800,
        surveySignalId: "anomaly-d",
        requiredSensingCapabilityId: "resonance-probe",
      },
    ],
    atmosphericSources: [
      {
        id: "atmospheric-plume-a",
        nameKey: "source.atmospheric-plume-a.name",
        material: "gas-0",
        x: 68,
        y: 24,
        width: 5,
        height: 5,
        units: 600,
        surveySignalId: "anomaly-c",
        requiredSensingCapabilityId: "core-probe",
      },
    ],
    terminalModules: [
      { id: "liquid-dock", nameKey: "terminal.module.liquid-dock.name", handlingState: "liquid", containmentCapabilities: ["corrosion-resistant"], capacity: 24, cost: 30, requiredTerminalCapabilityId: "liquid-outbound", inlet: { x: 1, y: 3, side: 1 } },
      { id: "gas-dock", nameKey: "terminal.module.gas-dock.name", handlingState: "gas", containmentCapabilities: [], capacity: 16, cost: 36, requiredTerminalCapabilityId: "gas-outbound", inlet: { x: 3, y: 1, side: 0 } },
      { id: "cryo-dock", nameKey: "terminal.module.cryo-dock.name", handlingState: "liquid", containmentCapabilities: ["cryogenic-rated", "hazard-isolated", "secure-chain"], capacity: 8, cost: 42, requiredTerminalCapabilityId: "specialized-inbound", inlet: { x: 0, y: 1, side: 2 } },
    ],
    width: 80,
    height: 60,
    buildMaterial: "plates",
    startStock: 600,
    factoryMin: 6,
    factoryMax: 20,
    factoryCellCost: 1,
    factoryRelocationFuelPerStep: 2,
    factoryRelocationDowntimeTicks: 24,
    beltCost: 1,
    elevatedSolid: {
      maxSupportSpan: 4,
      deckCostPerCell: 1,
      supportCost: 2,
    },
    portCost: 2,
    transportEveryTicks: 3,
    stagingCapacity: 24,
    terminalShipmentCapacity: 12,
    terminal: { x: 38, y: 26, width: 4, height: 4 },
    deposits: [
      {
        id: "ferrite-field",
        material: "ferrite",
        x: 15,
        y: 25,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "veined-field",
        material: "raw",
        x: 15,
        y: 35,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "north-ferrite",
        material: "ferrite",
        x: 51,
        y: 14,
        width: 6,
        height: 5,
        units: 3000,
      },
      {
        id: "east-veins",
        material: "raw",
        x: 58,
        y: 39,
        width: 7,
        height: 5,
        units: 3000,
      },
    ],
  },
  economy: {
    startFuel: 120,
    grant: 36,
    assistanceBelow: 2,
    milestoneExports: 1,
    marketEveryTicks: 50,
    defaultAssistancePackageId: "emergency-fuel",
    assistancePackages: [
      {
        id: "emergency-fuel",
        nameKey: "assistance.emergency-fuel.name",
        briefKey: "assistance.emergency-fuel.brief",
        fuelBelow: 2,
        grantFuel: 36,
        baseObligationFuel: 36,
        repeatObligationStepFuel: 12,
        continuationObligationFuel: 12,
        recoveryNetFuel: 24,
      },
    ],
    imports: [
      {
        id: "orbital-binder-crate",
        nameKey: "import.orbital-binder-crate.name",
        briefKey: "import.orbital-binder-crate.brief",
        materialId: "orbital-binder",
        quantity: 6,
        fuelCost: 42,
      },
      {
        id: "orbital-propellant-cylinder",
        nameKey: "import.orbital-propellant-cylinder.name",
        briefKey: "import.orbital-propellant-cylinder.brief",
        materialId: "orbital-propellant",
        quantity: 4,
        fuelCost: 32,
        terminalModuleId: "gas-dock",
      },
      {
        id: "orbital-coolant-canister",
        nameKey: "import.orbital-coolant-canister.name",
        briefKey: "import.orbital-coolant-canister.brief",
        materialId: "orbital-coolant",
        quantity: 4,
        fuelCost: 36,
        terminalModuleId: "cryo-dock",
      },
    ],
    exchange: [
      {
        materialId: "granules",
        baseCompensation: 12,
        floorCompensation: 4,
        baseDemandBps: 10000,
        saturationPerUnitBps: 1000,
        recoveryPerMarketTickBps: 250,
        requiredTerminalCapabilityId: "sealed-sample-outbound",
      },
      { materialId: "liquid-0", baseCompensation: 6, floorCompensation: 2, baseDemandBps: 10000, saturationPerUnitBps: 1000, recoveryPerMarketTickBps: 250, requiredTerminalCapabilityId: "liquid-outbound" },
      { materialId: "gas-0", baseCompensation: 8, floorCompensation: 3, baseDemandBps: 10000, saturationPerUnitBps: 1000, recoveryPerMarketTickBps: 250, requiredTerminalCapabilityId: "gas-outbound" },
      { materialId: "matrix", baseCompensation: 16, floorCompensation: 6, baseDemandBps: 10000, saturationPerUnitBps: 800, recoveryPerMarketTickBps: 250, demandRecoveryPerMarketTickBps: 100 },
      {
        materialId: "ferrite-ceramic",
        baseCompensation: 14,
        floorCompensation: 3,
        baseDemandBps: 10000,
        saturationPerUnitBps: 2500,
        recoveryPerMarketTickBps: 200,
        demandRecoveryPerMarketTickBps: 100,
      },
      {
        materialId: "catalyst-powder",
        baseCompensation: 9,
        floorCompensation: 5,
        baseDemandBps: 10000,
        saturationPerUnitBps: 500,
        recoveryPerMarketTickBps: 300,
        demandRecoveryPerMarketTickBps: 100,
      },
    ],
    demandShocks: [
      {
        id: "resonance-orbital-application",
        nameKey: "market.shock.resonance-orbital-application.name",
        briefKey: "market.shock.resonance-orbital-application.brief",
        materialId: "matrix",
        triggerReactionId: "sinter-orbital-binder",
        demandDeltaBps: 5000,
      },
    ],
    orders: [
      {
        id: "granules-procurement",
        nameKey: "order.granules-procurement.name",
        briefKey: "order.granules-procurement.brief",
        materialId: "granules",
        quantity: 4,
        durationTicks: 6000,
        rewardFuel: 24,
      },
      {
        id: "matrix-procurement",
        nameKey: "order.matrix-procurement.name",
        briefKey: "order.matrix-procurement.brief",
        materialId: "matrix",
        quantity: 3,
        durationTicks: 8000,
        rewardFuel: 30,
      },
    ],
    directives: [
      {
        id: "sealed-thermal-study",
        nameKey: "directive.sealed-thermal-study.name",
        briefKey: "directive.sealed-thermal-study.brief",
        operationId: "heat",
        inputMaterialId: "raw",
        processConditionId: "sealed",
        durationTicks: 6000,
        rewardFuel: 18,
      },
    ],
    propertyDirectives: [
      {
        id: "matrix-local-route",
        nameKey: "directive.matrix-local-route.name",
        briefKey: "directive.matrix-local-route.brief",
        propertyKey: "property.matrix-local-route.name",
        targetMaterialId: "matrix",
        solutionReactionIds: ["sinter-catalyst"],
        durationTicks: 10000,
        rewardFuel: 0,
        rewardImportSupplyId: "orbital-coolant-canister",
      },
    ],
    terminalCapabilities: [
      {
        id: "sealed-sample-outbound",
        nameKey: "terminal.capability.sealed-sample-outbound.name",
      },
      { id: "liquid-outbound", nameKey: "terminal.capability.liquid-outbound.name" },
      { id: "gas-outbound", nameKey: "terminal.capability.gas-outbound.name" },
      { id: "specialized-inbound", nameKey: "terminal.capability.specialized-inbound.name" },
    ],
    milestones: [
      {
        id: "sealed-study-certified",
        nameKey: "milestone.sealed-study-certified.name",
        hintKey: "milestone.sealed-study-certified.hint",
        requires: [
          {
            type: "reaction-confirmed",
            reactionId: "heat-raw-sealed",
          },
        ],
        unlockTerminalCapabilityIds: ["sealed-sample-outbound"],
      },
      { id: "liquid-study-certified", nameKey: "milestone.liquid-study-certified.name", hintKey: "milestone.liquid-study-certified.hint", requires: [{ type: "reaction-confirmed", reactionId: "liquefy-raw" }], unlockTerminalCapabilityIds: ["liquid-outbound"] },
      { id: "gas-study-certified", nameKey: "milestone.gas-study-certified.name", hintKey: "milestone.gas-study-certified.hint", requires: [{ type: "reaction-confirmed", reactionId: "vaporize-liquid-0" }], unlockTerminalCapabilityIds: ["gas-outbound"] },
      {
        id: "specialized-handling-certified",
        nameKey: "milestone.specialized-handling-certified.name",
        hintKey: "milestone.specialized-handling-certified.hint",
        requires: [{ type: "milestone-completed", milestoneId: "sealed-study-certified" }],
        unlockTerminalCapabilityIds: ["specialized-inbound"],
      },
      {
        id: "resonance-survey-certified",
        nameKey: "milestone.resonance-survey-certified.name",
        hintKey: "milestone.resonance-survey-certified.hint",
        requires: [{ type: "reaction-confirmed", reactionId: "collect-gas-0" }],
        unlockTerminalCapabilityIds: [],
      },
    ],
  },
});
