import { validateContent } from "./schema";
export const fixture = validateContent({
  version: "world-01-v6",
  tickMs: 100,
  materials: [
    {
      id: "ferrite",
      nameKey: "material.ferrite.name",
      color: "#a88d78",
      known: true,
    },
    {
      id: "plates",
      nameKey: "material.plates.name",
      color: "#b7c6ad",
      known: true,
    },
    {
      id: "raw",
      nameKey: "material.raw.name",
      color: "#c8aa73",
      known: true,
    },
    {
      id: "granules",
      nameKey: "material.granules.name",
      color: "#aadea0",
      known: false,
    },
    {
      id: "residue",
      nameKey: "material.residue.name",
      color: "#b298c4",
      known: false,
    },
  ],
  operations: [
    { id: "crush", nameKey: "operation.crush.name" },
    { id: "heat", nameKey: "operation.heat.name" },
  ],
  machines: [
    {
      id: "extractor",
      nameKey: "machine.extractor.name",
      role: "extractor",
      operations: [],
      capacity: 8,
      fuel: 1,
      durationTicks: 20,
      width: 2,
      height: 2,
      cost: 18,
    },
    {
      id: "crusher",
      nameKey: "machine.crusher.name",
      role: "processor",
      operations: ["crush"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 24,
    },
    {
      id: "furnace",
      nameKey: "machine.furnace.name",
      role: "processor",
      processConditionId: "ambient",
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 26,
    },
    {
      id: "sealed-furnace",
      nameKey: "machine.sealed-furnace.name",
      role: "processor",
      processConditionId: "sealed",
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 26,
    },
    {
      id: "oversealed-furnace",
      nameKey: "machine.oversealed-furnace.name",
      role: "processor",
      processConditionId: "oversealed",
      unlock: {
        reactionId: "heat-raw-sealed",
        hintKey: "machine.oversealed-furnace.unlock-hint",
      },
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 30,
    },
  ],
  storages: [
    {
      id: "depot",
      nameKey: "storage.depot.name",
      capacity: 40,
      width: 3,
      height: 2,
      cost: 30,
    },
  ],
  reactions: [
    {
      id: "press-ferrite",
      operation: "crush",
      input: "ferrite",
      inputAmount: 2,
      output: "plates",
      outputAmount: 6,
      observationKey: "reaction.press-ferrite.observation",
      known: true,
    },
    {
      id: "crush-raw",
      operation: "crush",
      input: "raw",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.crush-raw.observation",
      known: false,
    },
    {
      id: "heat-raw",
      operation: "heat",
      processConditionId: "ambient",
      input: "raw",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-raw.observation",
      known: false,
    },
    {
      id: "heat-raw-sealed",
      operation: "heat",
      processConditionId: "sealed",
      input: "raw",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observationKey: "reaction.heat-raw-sealed.observation",
      known: false,
    },
    {
      id: "heat-raw-oversealed",
      operation: "heat",
      processConditionId: "oversealed",
      input: "raw",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observationKey: "reaction.heat-raw-oversealed.observation",
      hazard: {
        id: "chamber-blowout",
        nameKey: "hazard.chamber-blowout.name",
        observationKey: "hazard.chamber-blowout.observation",
      },
      known: false,
    },
  ],
  site: {
    width: 80,
    height: 60,
    buildMaterial: "plates",
    startStock: 600,
    factoryMin: 6,
    factoryMax: 20,
    factoryCellCost: 1,
    beltCost: 1,
    portCost: 2,
    transportEveryTicks: 3,
    stagingCapacity: 24,
    terminal: { x: 38, y: 26, width: 4, height: 4 },
    deposits: [
      {
        id: "ferrite-field",
        material: "ferrite",
        x: 15,
        y: 25,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "veined-field",
        material: "raw",
        x: 15,
        y: 35,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "north-ferrite",
        material: "ferrite",
        x: 51,
        y: 14,
        width: 6,
        height: 5,
        units: 3000,
      },
      {
        id: "east-veins",
        material: "raw",
        x: 58,
        y: 39,
        width: 7,
        height: 5,
        units: 3000,
      },
    ],
  },
  economy: {
    startFuel: 120,
    grant: 36,
    assistanceBelow: 2,
    milestoneExports: 1,
    marketEveryTicks: 50,
    defaultAssistancePackageId: "emergency-fuel",
    assistancePackages: [
      {
        id: "emergency-fuel",
        nameKey: "assistance.emergency-fuel.name",
        briefKey: "assistance.emergency-fuel.brief",
        fuelBelow: 2,
        grantFuel: 36,
        baseObligationFuel: 36,
        repeatObligationStepFuel: 12,
        continuationObligationFuel: 12,
        recoveryNetFuel: 24,
      },
    ],
    exchange: [
      {
        materialId: "granules",
        baseCompensation: 12,
        floorCompensation: 4,
        baseDemandBps: 10000,
        saturationPerUnitBps: 1000,
        recoveryPerMarketTickBps: 250,
        requiredTerminalCapabilityId: "sealed-sample-outbound",
      },
    ],
    orders: [
      {
        id: "granules-procurement",
        nameKey: "order.granules-procurement.name",
        briefKey: "order.granules-procurement.brief",
        materialId: "granules",
        quantity: 4,
        durationTicks: 6000,
        rewardFuel: 24,
      },
    ],
    directives: [
      {
        id: "sealed-thermal-study",
        nameKey: "directive.sealed-thermal-study.name",
        briefKey: "directive.sealed-thermal-study.brief",
        operationId: "heat",
        inputMaterialId: "raw",
        processConditionId: "sealed",
        durationTicks: 6000,
        rewardFuel: 18,
      },
    ],
    terminalCapabilities: [
      {
        id: "sealed-sample-outbound",
        nameKey: "terminal.capability.sealed-sample-outbound.name",
      },
    ],
    milestones: [
      {
        id: "sealed-study-certified",
        nameKey: "milestone.sealed-study-certified.name",
        hintKey: "milestone.sealed-study-certified.hint",
        requires: [
          {
            type: "reaction-confirmed",
            reactionId: "heat-raw-sealed",
          },
        ],
        unlockTerminalCapabilityIds: ["sealed-sample-outbound"],
      },
    ],
  },
});
