import { validateContent } from "./schema";
export const fixture = validateContent({
  version: "world-01-v2",
  tickMs: 100,
  materials: [
    {
      id: "ferrite",
      name: "Ferrite rubble",
      color: "#a88d78",
      exportValue: 0,
      known: true,
    },
    {
      id: "plates",
      name: "Structural plates",
      color: "#b7c6ad",
      exportValue: 0,
      known: true,
    },
    {
      id: "raw",
      name: "Veined ore",
      color: "#c8aa73",
      exportValue: 0,
      known: true,
    },
    {
      id: "granules",
      name: "Conductive granules",
      color: "#aadea0",
      exportValue: 12,
      known: false,
    },
    {
      id: "residue",
      name: "Vitrified residue",
      color: "#b298c4",
      exportValue: 0,
      known: false,
    },
  ],
  operations: [
    { id: "crush", name: "Crush" },
    { id: "heat", name: "Heat" },
  ],
  machines: [
    {
      id: "extractor",
      name: "Extractor",
      role: "extractor",
      operations: [],
      capacity: 8,
      fuel: 1,
      durationTicks: 20,
      width: 2,
      height: 2,
      cost: 18,
    },
    {
      id: "crusher",
      name: "Crusher",
      role: "processor",
      operations: ["crush"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 24,
    },
    {
      id: "furnace",
      name: "Furnace",
      role: "processor",
      operations: ["heat"],
      capacity: 12,
      fuel: 2,
      durationTicks: 30,
      width: 2,
      height: 2,
      cost: 26,
    },
  ],
  reactions: [
    {
      id: "press-ferrite",
      operation: "crush",
      input: "ferrite",
      inputAmount: 2,
      output: "plates",
      outputAmount: 6,
      observation:
        "Ferrite compacts into structural plates for local construction.",
      known: true,
    },
    {
      id: "crush-raw",
      operation: "crush",
      input: "raw",
      inputAmount: 2,
      output: "granules",
      outputAmount: 1,
      observation:
        "Fracturing the ore releases conductive grains. The company accepts this material for fuel.",
      known: false,
    },
    {
      id: "heat-raw",
      operation: "heat",
      input: "raw",
      inputAmount: 2,
      output: "residue",
      outputAmount: 1,
      observation:
        "The sample vitrifies under heat. It has no export value; mechanical processing remains worth investigating.",
      known: false,
    },
  ],
  site: {
    width: 80,
    height: 60,
    buildMaterial: "plates",
    startStock: 600,
    factoryMin: 6,
    factoryMax: 20,
    factoryCellCost: 1,
    beltCost: 1,
    portCost: 2,
    transportEveryTicks: 3,
    terminal: { x: 38, y: 26, width: 4, height: 4 },
    deposits: [
      {
        id: "ferrite-field",
        material: "ferrite",
        x: 15,
        y: 25,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "veined-field",
        material: "raw",
        x: 15,
        y: 35,
        width: 6,
        height: 6,
        units: 3000,
      },
      {
        id: "north-ferrite",
        material: "ferrite",
        x: 51,
        y: 14,
        width: 6,
        height: 5,
        units: 3000,
      },
      {
        id: "east-veins",
        material: "raw",
        x: 58,
        y: 39,
        width: 7,
        height: 5,
        units: 3000,
      },
    ],
  },
  economy: {
    startFuel: 120,
    grant: 36,
    assistanceBelow: 2,
    milestoneExports: 1,
  },
});
